
.SUFFIXES: .o .cpp .cc .hh .yy .dep

CFLAGS=\
	-Wall\
	-Wextra\
	-Wformat\
	-Winit-self\
	-Wuninitialized\
	-Wsuggest-attribute=pure\
	-Wsuggest-attribute=const\
	-Wsuggest-attribute=noreturn\
	-Wshadow\
	-Wwrite-strings\
	-Wconversion\
	-Wlogical-op\
	-Wswitch\
	-I$(RPGML_SRC_ROOT)/libRPGML/\
 	-fPIC\
	-g -O0\
	-DDEBUG\

CXXFLAGS=$(CFLAGS)

LDFLAGS=\
	-lpthread\
	-L$(RPGML_SRC_ROOT)/libRPGML\

