
%.o.LDFLAGS: %.cc
	@echo Getting RPGML_LDFLAGS from $<
	@grep RPGML_LDFLAGS $< | sed "s/.*RPGML_LDFLAGS.*=//g" > $@

%.o.LDFLAGS: %.cpp
	@echo Getting RPGML_LDFLAGS from $<
	@grep RPGML_LDFLAGS $< | sed "s/.*RPGML_LDFLAGS.*=//g" > $@

%.o.CXXFLAGS: %.cc
	@echo Getting RPGML_CXXFLAGS from $<
	@grep RPGML_CXXFLAGS $< | sed "s/.*RPGML_CXXFLAGS.*=//g" > $@

%.o.CXXFLAGS: %.cpp
	@echo Getting RPGML_CXXFLAGS from $<
	@grep RPGML_CXXFLAGS $< | sed "s/.*RPGML_CXXFLAGS.*=//g" > $@

.%.cpp.dep: %.cpp %.o.CXXFLAGS
	@echo Generating dependencies for $<
	@g++ -M -MM -MG -MF $@ $(CXXFLAGS) $(shell cat $(shell echo $@ | sed -e "s/\/\./\//g" -e "s/^\.//g" -e "s/\.cpp\.dep//g" ).o.CXXFLAGS) $<

.%.cc.dep: %.cc %.o.CXXFLAGS
	@echo Generating dependencies for $<
	@g++ -M -MM -MG -MF $@ $(CXXFLAGS) $(shell cat $(shell echo $@ | sed -e "s/\/\./\//g" -e "s/^\.//g" -e "s/\.cpp\.dep//g" ).o.CXXFLAGS) $<

%.o: %.cpp %.o.CXXFLAGS
	g++ -c -o $@ $(CXXFLAGS) $(shell cat $(basename $@).o.CXXFLAGS) $<

%.o: %.cc %.o.CXXFLAGS
	g++ -c -o $@ $(CXXFLAGS) $(shell cat $(basename $@).o.CXXFLAGS) $<

libRPGML_%.so: RPGML_%.o RPGML_%.o.LDFLAGS RPGML_%.o.CXXFLAGS
	g++ -shared $< $(LDFLAGS) $(shell cat $<.LDFLAGS) $(CXXFLAGS) $(shell cat $<.CXXFLAGS) -lRPGML -o $@

.rerun_stest:
	@touch $@

%.pretty: %.rpgml .rerun_stest $(PRETTYPRINTER) Makefile
	@echo "Prettyprinting $<"
	@cd ./$(dirname $@) && RPGML_PATH="$(RPGML_SRC_ROOT)/ROOT:." $(PRETTYPRINTER) $(notdir $<) > $(notdir $@)

%.output: %.pretty %.expected .rerun_stest $(RPGML) Makefile
	@echo "Running $<"
	@cd ./$(dirname $@) && RPGML_PATH="$(RPGML_SRC_ROOT)/ROOT:." $(RPGML) $(notdir $<) > $(notdir $@)
	@diff -udab $@ $(<:.pretty=.expected)


